export const BLOG_REDIRECTS = Object.freeze({
  'merge-pdf-without-upload': '/guides/how-to-merge-pdf-files-without-uploading/',
  'minify-pdf-without-upload': '/guides/how-to-compress-pdf-without-losing-quality/',
  'lock-pdf-without-upload': '/guides/how-to-password-protect-a-pdf-before-emailing/',
  'unlock-pdf-without-upload': '/guides/how-to-remove-a-pdf-password-you-know/',
  'split-pdf-without-upload': '/guides/how-to-split-one-pdf-into-multiple-files/',
  'rotate-pdf-without-upload': '/guides/how-to-rotate-one-page-in-a-pdf/',
  'organize-pdf-without-upload': '/guides/how-to-reorder-and-delete-pdf-pages/',
  'crop-pdf-without-upload': '/guides/how-to-crop-pdf-margins-for-printing/',
  'watermark-without-upload': '/guides/how-to-add-a-watermark-to-a-pdf/',
  'page-numbers-without-upload': '/guides/how-to-add-page-numbers-to-a-pdf/',
  'pdf-to-jpg-without-upload': '/guides/how-to-convert-pdf-to-jpg-locally/',
  'pdf-to-docx-without-upload': '/guides/how-to-convert-pdf-to-word-without-uploading/',
  'jpg-to-pdf-without-upload': '/guides/how-to-convert-jpg-to-pdf-for-free/',
  'docx-to-pdf-without-upload': '/guides/how-to-convert-docx-to-pdf-in-browser/',
  'e-sign-pdf-online': '/guides/how-to-add-a-signature-image-to-a-pdf-locally/',
  'e-sign-pdf-without-upload': '/guides/how-to-add-a-signature-image-to-a-pdf-locally/',
  'fill-pdf-forms-online': '/guides/how-to-fill-and-sign-a-pdf-form-before-sending-it/',
  'fill-pdf-forms-without-upload': '/guides/how-to-fill-and-sign-a-pdf-form-before-sending-it/',
  'html-to-pdf-without-upload': '/guides/how-to-convert-html-to-pdf-locally/',
  'google-ads-content-support': '/advertising-disclosure/',
  'images-bulk-image-compression-guide': '/image-workflows/',
  'images-bulk-resize-listings-guide': '/image-workflows/',
  'images-convert-to-jpg-guide': '/image-workflows/',
  'images-remove-background-product-photos-guide': '/image-workflows/',
  'images-blur-faces-before-sharing-guide': '/image-workflows/',
  'eis-passport-photo-checklist': '/image-workflows/',
  'eis-employee-id-photo-standard-guide': '/image-workflows/',
  'eis-social-content-production-workflow': '/image-workflows/',
  'eis-visa-photo-resubmission-checklist': '/image-workflows/',
  'pdf-visa-application-packet-checklist': '/pdf-workflows/',
  'pdf-employee-onboarding-doc-workflow': '/pdf-workflows/',
  'pdf-confidential-client-report-workflow': '/pdf-workflows/',
  'pdf-edit-via-docx-and-back-workflow': '/pdf-workflows/',
  'pdf-fill-sign-private-workflow': '/guides/how-to-fill-and-sign-a-pdf-form-before-sending-it/',
  'html-to-image-launch-posts-workflow': '/image-workflows/',
  'prepare-images-for-strict-upload-portals': '/image-workflows/',
  'compress-vs-resize-for-image-kb-limits': '/image-workflows/',
  'heic-to-jpg-before-form-submission': '/blog/convert-heic-png-and-webp-for-easier-delivery/',
  'png-to-jpg-for-smaller-delivery-files': '/blog/convert-heic-png-and-webp-for-easier-delivery/',
  'blur-faces-before-sharing-team-photos': '/image-workflows/',
  'remove-background-without-fake-product-edges': '/image-workflows/',
  'watermark-images-for-public-previews': '/image-workflows/',
  'video-to-gif-for-product-changelog-notes': '/blog/turn-short-videos-into-gifs-for-product-updates/',
  'use-pdf-tools-android-app-without-cloud-uploads': '/guides/private-pdf-tools-android-app-free-download/',
  'merge-pdfs-on-android-for-assignments': '/guides/how-to-merge-pdf-files-without-uploading/',
  'compress-pdfs-on-android-before-email': '/guides/how-to-compress-pdf-for-email/',
  'organize-pdf-pages-on-phone-before-sharing': '/guides/how-to-reorder-and-delete-pdf-pages/',
  'pdf-inspector-checks-before-mobile-sharing': '/guides/how-to-check-pdf-metadata-page-size-and-password-status-locally/',
  'lock-pdfs-on-android-before-client-handoff': '/guides/how-to-password-protect-a-pdf-before-emailing/',
  'convert-pdf-to-word-on-android-for-rework': '/guides/how-to-convert-pdf-to-word-without-uploading/',
  'pdf-to-jpg-on-phone-for-page-previews': '/guides/how-to-convert-pdf-to-jpg-locally/',
  'private-pdf-workflow-for-freelancers': '/guides/how-to-prepare-a-pdf-for-client-delivery/',
  'local-first-pdf-workflow-for-office-staff': '/guides/how-to-send-private-pdf-files-without-uploading-them-first/',
  'android-pdf-app-vs-browser-pdf-tools': '/guides/private-pdf-tools-android-app-free-download/',
});

export const BLOG_GONE_SLUGS = Object.freeze([
  'student-visa-application-story',
  'story-operations-team-privacy-first-daily-files',
  'story-remote-hr-private-onboarding-routine',
  'story-student-scholarship-document-routine',
]);

const retiredBlogSlugs = new Set([...Object.keys(BLOG_REDIRECTS), ...BLOG_GONE_SLUGS]);

export function isRetiredBlogSlug(slug) {
  return retiredBlogSlugs.has(String(slug || '').trim());
}
